# Generated by Django 4.1.7 on 2023-03-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
