# Generated by Django 4.1.7 on 2023-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpage_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='likes',
        ),
    ]
