# Generated by Django 4.1.7 on 2023-03-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_cta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='cta',
            new_name='content',
        ),
    ]
